name = "fkMigration"
uuid = "c1a29864-aa63-11e9-0d3a-11cea8d3e6a9"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"

[compat]
julia = "^1.1"
